"""add withdrawal_date to expenses

Revision ID: af56c296de5b
Revises: d1d104a83d5b
Create Date: 2026-04-05 23:38:53.594656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af56c296de5b'
down_revision: Union[str, None] = 'd1d104a83d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('withdrawal_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'withdrawal_date')
    # ### end Alembic commands ###
